### ISSUE TITLE
Unexpected Spanner client library timeout when customer debugs their code 

### ISSUE THREAD

**Issue by skuruppu** [googleapis/nodejs-spanner#1059]
A customer has reported that when using the Node js client library for spanner (^4.6.2) it throws a "10 ABORTED: Transaction was aborted. Idle for over 10 seconds." error message when debugging and the breakpoint stops the execution by slightly more than 10 seconds (15- 30 seconds).

We discussed that [Cloud Spanner can abort transactions](https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions#idle-transactions) that have been idle for over 10 seconds so this should be expected. There is no parameter that can be configured to change this behavior.

The customer reported that they've only seen this error happen when setting a breakpoint in their code but they can't reproduce this in the code samples we provide.

So opening this bug to have a further discussion and perhaps the customer can provide some example code that they've tried.

CC @olavloite @AVaksman

**Comment by olavloite** [comment]
I've tested this with a slightly modified version of the `updateUsingDml` sample in the repository, and I'm able to reproduce it. There are however a couple of things to take into consideration:

1. Cloud Spanner _can_ abort a transaction that has been idle for 10 seconds, but it's not a given that it _must_ happen. Using a somewhat higher timeout in your code than 10 seconds will therefore give you a better chance that the transaction is consistently aborted by Cloud Spanner.
1. Cloud Spanner will only abort the transaction if it has already taken some locks, i.e. it has already executed at least one statement. If you start the transaction but wait for X seconds _before_ executing any statements, the transaction will most probably not be aborted.

An example that will consistently abort the transaction is given below.

```javascript
function updateUsingDml(instanceId, databaseId, projectId) {
  // [START spanner_dml_standard_update]
  // Imports the Google Cloud client library
  const {Spanner} = require('@google-cloud/spanner');

  // Creates a client
  const spanner = new Spanner({
    projectId: projectId,
  });

  // Gets a reference to a Cloud Spanner instance and database
  const instance = spanner.instance(instanceId);
  const database = instance.database(databaseId);

  let attempts = 0;
  database.runTransaction(async (err, transaction) => {
    if (err) {
      console.error(err);
      return;
    }
    try {
      attempts++;
      console.log(`Transaction attempt number ${attempts}`);

      // Wait 20 seconds before the update statement. This will not have any effect
      // on the transaction, as it has not yet executed any statements and therefore
      // also not taken any locks.
      await new Promise(resolve => setTimeout(resolve, 20000));

      console.log('Trying to execute an update statement');
      const [rowCount] = await transaction.runUpdate({
        sql: `UPDATE MyTable SET ColString = 'foo'
          WHERE ColInt64 = 1`,
      });
      console.log(`Successfully updated ${rowCount} record(s).`);

      // Wait 20 seconds after the update statement. This will abort the transaction.
      await new Promise(resolve => setTimeout(resolve, 20000));

      console.log('Trying to commit the transaction');
      await transaction.commit();
      console.log('Successfully committed the transaction');
    } catch (err) {
      console.error('ERROR:', err);
    } finally {
      // Close the database when finished.
      await database.close();
    }
  });
  // [END spanner_dml_standard_update]
}
```

Running the above code should cause the following output in the console:

```
Transaction attempt number 1
Trying to execute an update statement
Successfully updated 1 record(s).
Trying to commit the transaction
Transaction attempt number 2
Trying to execute an update statement
Successfully updated 1 record(s).
Trying to commit the transaction
Transaction attempt number 3
Trying to execute an update statement
Successfully updated 1 record(s).
Trying to commit the transaction
Transaction attempt number 4
...
```

**Comment by josecaodaglio** [comment]
Hello, thanks everybody. I am the customer who opened the SR and the problem happens 100% of the time no matter what editor I use (MS code, webstorm)


The case is as follow:

1- Start the program
2-  update the DB with no blind transactions (the actual DML instead of .insert or .upsert). 
3- I pause to debug. If I spend more than 10s, I will get an error next time I touch spanner

@olavloite you said that it is possible to increase the timeout but I haven't found a parameter for transaction, just session. Support told me the same.

Thanks

**Comment by olavloite** [comment]
Hi @josecaodaglio 

If you follow the steps that you mentioned above, then the transaction will (in basically all cases) be aborted, which means that the next time you execute any statement against the Spanner database (SELECT, UPDATE, DELETE, ...), the statement will return an `ABORTED` error. So that is expected.

However, if you use the standard transaction functionality in the client library as in my example above, the transaction should automatically be retried and will normally succeed during the second attempt, unless you still have the breakpoint activated.

What I meant by 
> Using a somewhat higher timeout in your code than 10 seconds...

was only related to my example above. I had understood the problem as that you were not able to reproduce the aborted transactions _unless_ you had set a breakpoint, and that if you only introduced an artificial wait the transaction would not be aborted. My point was that if you waited _exactly_ 10 seconds, then there was a possibility that Spanner would not abort your transaction. That is the reason that my example waits for 20 seconds.

There is no possibility to increase this timeout. It is a timeout that is determined by the backend, and the backend does not allow the value of this timeout to be changed.

I hope this clear it up a little. If not, don't hesitate to ask :-)

**Comment by josecaodaglio** [comment]
Thanks Olav. Please let me confirm my understanding:

1- In my case, I have 100% sure that transaction will abort. Instead of using database.runTransaction I get the transaction directly from the pool, which as I understand now, it is not common.

2- If I use database.runTransaction I might have additional time before have the mentioned error.

If this is the case, let me show you why I get connections directly from the pool and why runTransaction might not work for me.

my case is like that

... usual code...
```
 await doSomething;
// Please note the await bellow
await CloudSpanner.dbOperation(async (transaction) => {
      .. do a lot of async stuff
      return myOwnStruct


});

```
And here is my dbOperation:

```
public static async dbOperation<T>(operation: (conn: SpannerWrite) => Promise<T>, doCommit: boolean = true): Promise<T> {
        let conn: SpannerWrite;
        let resultError: Error;
        let result: T;
        try {
            conn = await CloudSpanner.getWriteSession();
            result = await operation(conn);
            if (doCommit) {
                await conn.commit();
            }
        } catch (err) {
            if (conn) {
                await conn.rollback();
            }
            resultError = err;
        } finally {
            if (conn) {
                conn.release();
            };
            if (resultError) {
                throw resultError;
            } else {
                return result;
            };
        };
    }

```

The problem using database.runTransaction inside my own dbOperaction is that it is not async. So, It will jump directly to the next line after it, before doing what it has to do. 

As it is designed, I could even transform it into a promise.

So, if I understand right and runTransaction is more resilient, I'd like to know if there is something special in the way runTransaction consumes the pool so I could use the same techinique.

Thanks

**Comment by olavloite** [comment]
> 1- In my case, I have 100% sure that transaction will abort. Instead of using database.runTransaction I get the transaction directly from the pool, which as I understand now, it is not common.

Correct. The recommended way is to use `database.runTransaction` or `database.runTransactionAsync`. Those functions will automatically handle aborted transactions for you.

> 2- If I use database.runTransaction I might have additional time before have the mentioned error.

No, the function will not give you any additional time before a transaction is aborted by the backend, but it will automatically handle it for you. `database.runTransaction` will automatically retry the transaction using the same session if the original transaction is aborted.

If you for some reason cannot use `database.runTransaction` or `database.runTransactionAsync`, you should __always__ add your own retry logic to your transactions. Cloud Spanner [can abort any read/write transaction](https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions#retrying-aborted-transactions), not only those that are idle for more than 10 seconds. That would mean placing your transaction code in a loop with a try-catch block. If the transaction code throws an error with code `Aborted`, then you should retry the entire transaction. If the transaction throws an error with any other error code, that error should be propagated to the caller (or handled in some other way).

Based on your example above I think you should be able to use `database.runTransactionAsync` as  a drop-in replacement for your own code.

**Comment by josecaodaglio** [comment]
@olavloite this  `database.runTransactionAsync` definitively worked. Thanks a lot!

Is there an analog to readOnlyTransaction, something like `database.runReadOnlyAsync( (readOnly) =>... `?

Here is the actual version of what I had using you directions.



    ```
public static async dbOperation<T>(operation: (conn: SpannerWrite) => Promise<T>, doCommit: boolean = true): Promise<T> {

        let resultError: Error;
        let result: T;
        let write: SpannerWrite;

        await CloudSpanner.database.runTransactionAsync(async (transacion) => {
            try {
                write = new SpannerWrite(null, transacion);
                result = await operation(write);
                if (doCommit) {
                    await write.commit();
                }
            } catch (err) {
                if (write) {
                    await write.rollback();
                }
                resultError = err;
            }
        })
        if (resultError) {
            throw resultError;
        } else {
            return result;
        };
     }

```

**Comment by josecaodaglio** [comment]
@olavloite it seems that runTransactionAsync will retry the operation if any error occurs, the transactions are behaviouring as not exepcted.

In [1], we have the following

> 
In the event that an aborted error occurs, we will re-run the runFn in its entirety. If you prefer to handle aborted errors for yourself please **refer to Database#getTransaction.**

So to have my transactions running completely isolated no matter what the problem is, I think I will still need to get directly from the pool

[1] https://googleapis.dev/nodejs/spanner/latest/Database.html#runTransactionAsync

**Comment by olavloite** [comment]
> Is there an analog to readOnlyTransaction, something like `database.runReadOnlyAsync( (readOnly) =>... `?

No, but you don't need that either. Read-only transaction will not be aborted by Cloud Spanner, so you should be safe to use those by defining your own functions without any additional retry logic.

**Comment by olavloite** [comment]
> it seems that runTransactionAsync will retry the operation if any error occurs, the transactions are behaviouring as not exepcted.

I don't quite understand this statement. Your reference to the documentation clearly states that `runTransactionAsync` will retry __aborted errors__. It will not retry __any__ error.

> So to have my transactions running completely isolated no matter what the problem is, I think I will still need to get directly from the pool

No. The function that you provide to the `runTransactionAsync` will run in complete isolation from all other transactions. If the transaction is aborted by Cloud Spanner, the entire transaction will be retried as a new transaction, which is also completely isolated from all other transactions.

**Comment by josecaodaglio** [comment]
Hello @olavloite thanks for your patience. 

`In the event that an aborted error occurs, we will re-run the runFn in its entirety. If you prefer to handle aborted errors for yourself please refer to Database#getTransaction.`

Does this means that if may callback throws an error, runTransactionAsync will retry it?
Will runTransactionAsync execute a commit or it is up to you to commit?

What I tried to say in my last comment is that, as I use datastore, redis and spanner, I made the code in a specific way to avoid the most I could that it is possible to have a commit in the spanner and not an upsert in the datastore(so I commit spanner, simple upsert DS and run the scripts in redis) . And since I used runTransactionAsync, I have divergence between datastore and spanner twice, which I don't have for more than a year now.

So I am trying to figure out if there is a retry or an auto-commit etc.

Thanks

**Comment by olavloite** [comment]
> Does this means that if may callback throws an error, runTransactionAsync will retry it?

No. It will only retry if the callback throws an __aborted error__. An __aborted__ error is something that is thrown by Cloud Spanner when the transaction is aborted. If your callback throws any other kind of error, it will not be retried.

> Will runTransactionAsync execute a commit or it is up to you to commit?

Your callback function should call `transaction.commit()` or `transaction.rollback()`. `runTransactionAsync` will not commit the transaction automatically for you.

> What I tried to say in my last comment is that, as I use datastore, redis and spanner, I made the code in a specific way to avoid the most I could that it is possible to have a commit in the spanner and not an upsert in the datastore(so I commit spanner, simple upsert DS and run the scripts in redis) . And since I used runTransactionAsync, I have divergence between datastore and spanner twice, which I don't have for more than a year now.

> So I am trying to figure out if there is a retry or an auto-commit etc.

That's hard to tell without knowing the code. There should be no auto-commit, and also a retry should not really make a difference for that. When you execute `runTransactionAsync`, it will either return successfully indicating that the transaction succeeded, or it will throw an error indicating that the transaction failed. Whether the `runTransactionAsync` succeeded at the first attempt or needed one or more retries, should not make any difference for the rest of your code.

**Comment by josecaodaglio** [comment]
Hello @olavloite , so this is why runFn (the callback) must be idempotent. If an abort error happens, it will callback runFn again, is this correct?

**Comment by olavloite** [comment]
> so this is why runFn (the callback) must be idempotent.

Yes, at least when it comes to the state of your application it should be idempotent. In other words: You should for example not execute something like `x = x * 2`, where `x` is a global variable, from inside the `runFn` function, as the function might be executed multiple times.

It is however OK to execute non-idempotent SQL update statements from the `runFn` function, as the client library and Cloud Spanner will guarantee that the database transaction will only be executed once. So executing a statement like `UPDATE SOME_TABLE SET SOME_COLUMN=SOME_COLUMN*2 WHERE ID=1` is OK in `runFn`.

> If an abort error happens, it will callback runFn again, is this correct?

Yes, that is correct

**Comment by josecaodaglio** [comment]
Thanks @olavloite . IMHO you could assess other possibilities to deal with this. I have thousands of lines inside this runFn and it is impossible to be sure that everything is idempotent. I can't rerun the whole callback if there is an eventual semaphore or even a longer CPU operation in a single threaded nodejs. As far as I know, no other DB has this kind of requirements and off course Spanner is very sui generis but I let here my opinion as this generates a burden to developers. I don't think developer should be worried to create timeouts with 'select 1' as well.

Anyway, thanks a lot for your generous teachings.

**Comment by skuruppu** [comment]
Thanks for the discussion @josecaodaglio. I will close this issue now since the discussion has been resolved. Please reach out to us either through the support route or by opening a GitHub issue if there are any further questions or concerns.
