### ISSUE TITLE
Option to do non-locking reads in a R/W transaction that includes the DML changes

### ISSUE THREAD

**Issue by KennyCCK** [googleapis/nodejs-spanner#1350]
**Is your feature request related to a problem? Please describe.**
- Cloud Spanner documentation generally recommends to use Read-only transaction for reads whenever possible [1] because it does not acquire locks. 
- However, for use-cases with long R/W transactions, occasionally there might be needs to perform reads (that includes the DML changes) but as we know this ends up acquiring "shared reader lock" and tends to cause lock contentions in a multi-concurrency environment.
- If reads are obtained from Read-only transactions, they do not contain the DML changes within the R/W transaction.
- Even as a workaround to use Read-only transactions for reads, it can be confusing to maintain multiple transactions (have to purposely initialize two transactions for a single task, Read-only + R/W)

 **Describe the solution you'd like**
An option to do non-locking reads within R/W transactions that contain the DML changes

 **Describe alternatives you've considered**
Reads from Read-only transaction works for preventing lock contentions but the fact it does not include DML changes can be quite problematic in use cases with long R/W transactions

 **Additional context**
1. We know that MySQL allows explicit locking reads [2] by using SELECT ... FOR UPDATE or SELECT ... FOR SHARE.
2. It would appear that Cloud Spanner's R/W transaction reads are performing similar to SELECT ... FOR SHARE as default.
3. Cloud Spanner's whitepaper [3] described:

```
Like Bigtable, writes that occur in a transaction are
buffered at the client until commit.
```

as they are buffered on the client, would it possible to be referenced (or it is already doing so) and doing the reads without acquiring locks? (is the part about reads in a R/W transaction "must acquire locks" controlled by the server's absolute isolation level?)

[1] https://cloud.google.com/spanner/docs/transactions#read-write_transactions
[2] https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
[3] https://static.googleusercontent.com/media/research.google.com/en//archive/spanner-osdi2012.pdf

**Comment by skuruppu** [comment]
@KennyCCK unfortunately there's nothing we can do on the client side to do non-locking reads in a R/W transaction. Cloud Spanner R/W transactions use the [serializable](https://en.wikipedia.org/wiki/Isolation_(database_systems)#Serializable) isolation level to give the strictest consistency guarantees which means you have to take the locks and these decisions are made on the server side.

At the moment, Cloud Spanner doesn't let you configure the isolation level.

I'll close the issue but please reopen if you have any more questions.

**Comment by josecaodaglio** [comment]
Hello, just add the my point of view

In my perspective, there are a lot more to a database scale than being capable of insert thousands of lines.

AFAIK, Spanner is the only database that automatically assumes that you will change the data you read if it is inside a read/write transaction.

This characteristic affect a lot Spanner scalability when dealing with real world complex transactions. 
My case is like this:

Read "100 rows" in several tables that I am not intend to change
Change only two rows.

The problem here is that this generate an immense footprint that will harm several other transactions, neither of each would be change any of the data that in the end, will eventually be "wounded" and aborted.

So in this case, where the transactions are more sophisticated, your application won't scale. And as you can't [debug](https://github.com/googleapis/nodejs-spanner/issues/1349) and there is no easy way to find the offender, you can't fix as well.

So in my perspective

1- When you are aborted, the error (try {} catch (error)) should` should have an "offender" property showing exactly what DML/SQL wounded you. At least, this would allow you to try fix the problem.

2- As it seems that is impossible to set the isolation level, spanner should allow you to set if your select would lock by default or not and them implement the "select for update" feature to handle the cases (vast minority) that need to be locked.

**Comment by skuruppu** [comment]
Thanks @josecaodaglio for the background and for the suggestions. There's a lot to unpack here so I'll reply inline.

> Read "100 rows" in several tables that I am not intend to change
Change only two rows.

> The problem here is that this generate an immense footprint that will harm several other transactions, neither of each would be change any of the data and in the end, it will eventually be "wounded" and aborted.

There might be a misunderstanding here. The reads in a RW transaction only take read locks. These don't wound other transactions. **Only** writes in a transaction can wound other transactions, and **only** when other transactions have read the rows being written to.

Reads can be wounded by writes occurring in other transactions, but this is because the principle of a transaction is that anything that is read should be the latest value at the time of commit - if it is updated between the read and the commit, then the read value is no longer the latest.

There's also an assumption here that getting an aborted transaction is bad. But in the case of Spanner, with the consistency guarantees it gives, it's expected that transactions will abort. This is why client libraries automatically retry them to a certain extent. So if you're still seeing aborted transactions after the client retries, then there's probably something we can help with to rethink how the queries should be structured. I'd encourage you to reach out to us via the support channel so that we can help you. Or if you're comfortable doing it on GitHub, that's also fine.

Here are some suggestions on how to run the type of query you mentioned:
1. Consider a reconciliation transaction that adds up a list of ledger items and writes the total as at a timestamp. If a ledger row is inserted or updated during the transaction by another process, the transaction would need to be retried to give a correct total value.
2. If it's not important that the rows you have read have the latest data, then you can either read them outside of the RW transaction, or blind-write your updates.
3. Consider a dual-read pattern:
  - A set of rows are read outside of a transaction to determine which subset of rows need to be updated (according to a condition).
  - In the RW transaction, the subset of rows are re-read to verify that they still need to be updated. This then locks these rows.
  - If the rows in a state that can be updated, then this subset of rows are updated and committed.

> 1- When you are aborted, the error (try {} catch (error)) should` should have an "offender" property showing exactly what DML/SQL wounded you. At least, this would allow you to try fix the problem.

There are lots of reasons that can cause a transaction to be aborted. e.g. mutations were added using the Mutation API; the backend may have created some additional mutations under the hood (e.g. application code only changes column C in table T, but some generated columns that depend on C may be re-calculated, and some index may be updated). At commit time, the transaction is a list of mutations. Spanner only knows that it conflicts with some other list of mutations coming from some other transaction but it doesn't know which one.

> 2- As it seems that is impossible to set the isolation level, spanner should allow you to set if your select would lock by default or not and them implement the "select for update" feature to handle the cases (vast minority) that need to be locked.

AFAIK, in other databases, SELECT FOR UPDATE lock the rows being read which blocks other transactions. Spanner by default opts for a more cooperative system which allows multiple simultaneous readers. If it helps, we recently released the [LOCK_SCANNED_RANGES](https://cloud.google.com/spanner/docs/query-syntax#statement-hints) hint which creates blocking exclusive locks on read and can be useful for rows with high contention.

**Comment by josecaodaglio** [comment]
Hello @skuruppu 

> There might be a misunderstanding here. The reads in a RW transaction only take read locks. These don't wound other transactions. Only writes in a transaction can wound other transactions, and only when other transactions have read the rows being written to.

Could you explain to me this behavior based on what you said?

-> rw tr 1 
select * from accounts;                                       
-> rw tr2
select * from accounts;  
update Accounts set type = 'Account' where UserId=2;
-> rw tr1
update Accounts set type = 'Account' where UserId=3;
-> rw tr2
commit; // blocked
-> rw tr1
commit; // ok
-> rw tr 2
// = "Transaction was aborted. It was wounded by a higher priority transaction due to conflict on keys in range [[3], [3])

I could write much more subtle use cases. I had just one case that was basically this:
- The user clicks in a menu (in the browser)
- Before executing the menu, the server recheck if the user has access. The controller opens a RW transaction (same for all menus), recheck the menu rights, pass the same connection to the business controller to execute the business transaction
- This business transactions changed the rights of the user to support a specific business case

So I had a lot of wounded transaction here because all the times menus were being rechecked. No writes, no logs, just reading. I changed this recheck to read, and no more wounded. So reads were generating wounded transactions

Before I go further and answer to the last part of the email, please confirm that we are in the same page.

Just as a side note, Oracle have the default isolation level TRANSACTION_READ_COMMITTED, so it will release the query lock after the statement is issued. So it won't have any problem running the same transaction.  If you want a more restrict isolation level, you set your Session to TRANSACTION_SERIALIZABLE

It seems to me that spanner is design to smash thousands of transactions not for complex transactions, like a compromise between nosSql and RDBMs. To my perspective, to be scalable you must give to the developer options to handle isolation level.

Thanks

**Comment by skuruppu** [comment]
Thanks for the example. Here it is annotated with what locks will be taken:

-> rw tr 1
select * from accounts; **// read locks all rows in accounts**
-> rw tr2
select * from accounts; **// read locks all rows in accounts**
update Accounts set type = 'Account' where UserId=2; **// rows where UserId=2 takes a read lock**
-> rw tr1
update Accounts set type = 'Account' where UserId=3; **// rows where UserId=3 takes a read lock**
-> rw tr2
commit; // blocked **// tr2 will block to upgrade rows where UserId=2 to write locks**
-> rw tr1
commit; // ok **// tr1 will block to upgrade rows where UserId=3 to write locks. Since tr2 read these rows, and tr1 started before tr2, tr1 will wound tr2 and complete the update.**
-> rw tr 2
// = "Transaction was aborted. It was wounded by a higher priority transaction due to conflict on keys in range [[3], [3])

In this particular case, you would avoid the wounding if the reads for tr1 and tr2 had WHERE clauses for UserId=2 and UserId=3, respectively. I don't know if this is possible for the actual queries you have in your application. For example, there might be overlaps in the WHERE clause.

Regarding the isolation levels, I totally understand that it might be difficult to not have support for TRANSACTION_READ_COMMITTED. But you can get the same behavior by having the read component of tr1 and tr2 be done outside of the read/write transaction.

**Comment by josecaodaglio** [comment]
Hello @skuruppu 

I do understand what and where the locks are. My point was to emphasise how the read will lock the rows and indeed will generate wounded transaction even if the same data will not be changed. (more on this on the end)

> But you can get the same behavior by having the read component of tr1 and tr2 be done outside of the read/write transaction.

Here is the worst part to me, and where I think you guys are not getting the full context (I am facing tons of problems because of that and losing productivity) 

- Real world transactions are made by several developers inside several functions
- This functions are blackbox to other developers
- There is now way that a developer will inform to others and keep the documentation on what row is being updated in what function. 
- So, I can't assume the risk to read a stale data (what you have suggested) just reading the same set of rows that have been already updated in another part of the code made by another developer
- If you want a transaction to be consistent, you have to let the developer take care of the consistency level, because the downside of reading stale data inside a real world transaction is far worst than dealing with the downside of switching consistency levels.

So, by any means, I would have the same behavior as you told. Actually, the only case where I could have the same behavior is if my transaction are very simple.

The restriction that is being designed in Spanner means that it will fit if you want to insert thousand of rows and commit, like a compromise between a NoSQL and RDBMS. 

The tradeoff between the consistency level and scalability (real scalability, where your transaction will not be aborted all the time)  is very spread.

> To describe consistent transaction behavior when transactions run at the same time, database researchers have defined a transaction isolation model called serializability. The serializable mode of transaction behavior tries to ensure that transactions run in such a way that they appear to be executed one at a time, or serially, rather than concurrently.  **While this degree of isolation between transactions is generally desirable, running many applications in this mode can seriously compromise application throughput. Complete isolation of concurrently running transactions could mean that one transaction cannot perform an insert into a table being queried by another transaction. In short, **real-world** considerations usually require a compromise between perfect transaction isolation and performance.**

Please focus on the **real world** cases. Applications are not always short DMLs. 

So my suggestion is to at least implement `select for share` so you could set the default behavior to no abort the SQL that is made (or not, as the developer defines)

**Comment by skuruppu** [comment]
@josecaodaglio thanks a lot for the details. I passed your concerns and recommendations to the team so that they can take this into account when deciding to add future query hints or SQL syntax that may cover these cases.
