### ISSUE TITLE
Undocumented ability to set RequestOptions or CallOptions on many APIs

### ISSUE THREAD

**Issue by nielm** [googleapis/nodejs-spanner#1378]
It is possible to set a Request Priority or a deadline/timeout on some of the RPC calls by passing an Options Object wich contains a Gax CallOptions, and/or a RequestOptions object for example: 
* [Table.insert/update/upsert/replace/delete](https://googleapis.dev/nodejs/spanner/latest/Table.html#deleteRows)
* [Transaction.commit](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#commit)

~But it is not possible to set Priorities or deadlines on any of the APIs which read or Execute SQL queries or DML on the database.~

It is however not documented that it is poissible to set these options on the following APIs. The JSDoc does not mention the parameters.

* [Table.read](https://googleapis.dev/nodejs/spanner/latest/Table.html#read)
* [Transaction.run/runStream](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#run)
* [Transaction.read](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#read)
* [Database.run](https://googleapis.dev/nodejs/spanner/latest/Database.html#run)
* [Database.runPartitionedUpdate](https://googleapis.dev/nodejs/spanner/latest/Database.html#runPartitionedUpdate)

(and probably many others that I couldn't find) 

~It is often much more important to set deadlines and priorities on queries so that a response is either returned in a reasonable time, or the query fails, or that a long running DML operation occurs at a low priority.~

~This is possible by accessing the gRPC API directly, but not though the client libraries. ~

#### Environment details

OS: Debian Rodete (20210511.01.04RD)
node: v12.21.0
npm: 7.5.2
google-gax@2.13.0
grpc/grpc-js@1.3.2
grpc-gcp@0.3.3

**Comment by skuruppu** [comment]
Thanks for filing the issue @nielm. It should be possible to set all those options through the options fields available in each of those APIs. I think the problem is that the docs don't seem to correctly show all the fields that are available within an input parameter object when we extend interfaces. I'll need to follow up with the Node.js team to fix this.

- [Table.read](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/table.ts#L685) and [Transaction.read](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L615) takes in a [ReadRequest](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L91) which extends [RequestOptions](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L56) to provide a `gaxOptions` field and also `IRequestOptions` (which is the proto) where you can set the `priority`.
- [Transaction.run/runStream](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L751), [Database.run](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/database.ts#L2128) and [Database.runPartitionedUpdate](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/database.ts#L2160) takes in an [ExecuteSqlRequest](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L75) which extends [RequestOptions](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L56) to provide a `gaxOptions` field and also `IRequestOptions` (which is the proto) where you can set the `priority`.

I know how confusing these interfaces are. The issue is that we've had to introduce several new options over time, and since we're not allowed to make breaking changes to our APIs, every time there's a new option, we have to extend the interfaces to support the new fields :(

**Comment by nielm** [comment]
Confirmed that it is possible to set the timeouts (whether they work correctly is another issue: https://github.com/googleapis/gax-nodejs/issues/1013.

Changing title to reflect that the ability to set these options is not documented...

**Comment by nielm** [comment]
Example, for Table.read(). 

In the [source](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L91) a ReadRequest extends RequestOptions (which contains gaxOptions)  and takes a requestOptions object. 

The [JSDoc for this object](https://github.com/googleapis/nodejs-spanner/blob/de6e0e5115a3d3da5bfe5f941cbf8fc6165b4b68/src/transaction.ts#L398): does not mention this inheritence nor the additional requestOptions object.

**Comment by skuruppu** [comment]
Thanks for the fixes @laljikanjareeya.

I was looking through some of the links and there are a couple more issues that I noticed:
- [CommitOptions](https://googleapis.dev/nodejs/spanner/latest/global.html#CommitOptions) fields don't have links.
- [ExecuteSqlRequest](https://googleapis.dev/nodejs/spanner/latest/global.html#ExecuteSqlRequest) should contain a bunch of other options as it [extends a few interfaces](https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction.ts#L75).
- Should `object` be replaced with `ExecuteSqlRequest` for [Database.runPartitionedUpdate](https://googleapis.dev/nodejs/spanner/latest/Database.html#runPartitionedUpdate)?

**Comment by laljikanjareeya** [comment]
I will take a look.
