### ISSUE TITLE
Spanner sessions keep increasing

### ISSUE THREAD

**Issue by daneshka** [googleapis/nodejs-spanner#1432]
Our Spanner Sessions keep increasing until we restart the pods (we create a new database object on pod initialize).
https://github.com/googleapis/google-cloud-node

![image](https://user-images.githubusercontent.com/12647179/125810918-19958241-fc7b-4b0b-9ded-97ff0995f4a2.png)
 
We don't see any impact on the pods' memory and CPU. It looks like the only impact is on the max latency of the query-by-id and query-by-column

![image](https://user-images.githubusercontent.com/12647179/125642013-5a622539-714a-45c5-b35c-ff9aae54d856.png)

#### Environment details

  - OS:
alpine
  - Node.js version:
node:14
  - npm version:
6.14.13
  - `@google-cloud/spanner` version:
5.9.0

#### Steps to reproduce
We create a single database instance and we use that database for all queries and transactions. (please advise if that's the right approach).

```
            const queryOptions = { optimizerVersion: 'latest' };
            this.db = instance.database(databaseId, undefined, queryOptions);
```

**Comment by skuruppu** [comment]
@daneshka thanks for reporting the issue.

I wanted to ask some questions to understand the issue and the setup:
1. From the two graphs, is it safe to assume that this happens over a 7+ day period? I'm assuming this based on the x-axis of the second graph.
2. I assume that the number of sessions in the graph are across all the pods? How many pods were used here?
3. What is your session pool configuration? Do you have a custom config or do you use the defaults?
4. Do you have any QPS graphs for that time frame?

**Comment by daneshka** [comment]
@skuruppu 
1. That's true. I updated the screenshot to capture the dates.
2. We have 5 pods. They all use less than %20 of the resources.
3. We use the default configuration for the session pool
4. the QPS is between 3 to 22.  (please note that the QPS it's not increasing in that period in the other words there is no correlation between the QPS and the number of sessions)

**Comment by skuruppu** [comment]
Thanks for the details @daneshka. I will run a job to see if I can reproduce the issue.

In terms of expected behavior, the default session pool configuration means that each database instance would start with a minimum of [25 sessions](https://github.com/googleapis/nodejs-spanner/blob/cf78d4a046e40156ffa416b34faa92e3859e72d6/src/session-pool.ts#L159) and the pool can grow up to [100 sessions](https://github.com/googleapis/nodejs-spanner/blob/cf78d4a046e40156ffa416b34faa92e3859e72d6/src/session-pool.ts#L157). Assuming you're using a single database instance in each pod, then I expect the number of sessions to max out at 500 sessions across the 5 pods.

So it's very odd to see it grow up to 18k sessions. Also, it is absolutely the correct thing to do to create one database instance and reuse it over all queries.

While we work on the issue, out of curiosity, how are you getting the session counts? We do have a [method](https://github.com/googleapis/nodejs-spanner/blob/cf78d4a046e40156ffa416b34faa92e3859e72d6/src/session-pool.ts#L425) in the session pool for getting the current session count. So I just wanted to check with you if you're using that or some other means to get the number of sessions. 

Also, can you provide a small snippet of how you're running the query as well? Just to know which methods from the library you're using and how you're calling it.

**Comment by daneshka** [comment]
we use a [DataDog metric](https://docs.datadoghq.com/integrations/google_cloud_spanner/) `gcp.spanner.instance.session_count`

Each time we restart the pods, session count starts from about 300 (60 per pod). This number wouldn't be perfect because we use the `RollingUpdate` deployment strategy and the pods get updated one by one.

Please note that in some parts of the code we use transaction and in some other parts (mostly get queries) we query directly from the database object (we want to avoid range locking). We use these methods:
```
// delete
transaction.deleteRows(tableName, keys)
table.deleteRows(keys)
// run query
database.run(query)
transaction.run(query)
// insert
transaction.insert(tableName, rows)
table.insert(rows)
// update
transaction.update(tableName, rows)
table.update(rows)
//update query
transaction.runUpdate(query)
//begin transaction
database.getTransaction()
//commit transaction
transaction.commit()
```

**Comment by skuruppu** [comment]
I've been running various tests with both read-only and write queries, but I haven't been able to reproduce the issue. Since I don't have DataDog setup, I focused on looking at the session pool size reported by the client library.

Even though I was issuing queries at a rate where all the available 100 sessions in the pool are occupied, I didn't see any session leaks, the pool was maxed out at 100.

I also ran a test where I deliberately didn't call `transaction.commit()` to cause the session to leak, but even then, the client maxed out at 100 sessions and just got stuck not being able to serve any further requests.

I was also monitoring the `spanner.googleapis.com/instance/session_count` Cloud Monitoring metric while running the tests which I think is equivalent to the DataDog metric you're using. I noticed something interesting there, which is that as I was running the tests and cancelling the job, the session count reported by the backend kept growing.

![iLkYtN6pHDQTTqM](https://user-images.githubusercontent.com/951152/126265918-0992e215-6cb4-41fc-99ee-1d1b6858f8c1.png)

But there is an explanation for this behavior. When I kill the job, then I don't give the client the opportunity to clean up the sessions created in the backend by calling `session.delete()`. So the backend will keep those sessions around for 1 hour after which it will delete it for being an idle session. Hence the step up and step down behavior you see in the graph above.

So I was wondering if there was any chance that your pods may be restarting the jobs on their own periodically without calling `database.close()` first?

In any case, since I couldn't repro the issue, I'd also like @olavloite to take a look as well.

**Comment by skuruppu** [comment]
One thing that I forgot to mention is that, to explicitly check if there's a session leak, you can set the [`fail`](https://github.com/googleapis/nodejs-spanner/blob/cf78d4a046e40156ffa416b34faa92e3859e72d6/src/session-pool.ts#L117) option in `SessionPoolOptions` to `true` when creating the database instance. Then, if there is a session leak, and the pool gets maxed out, it will print a stack trace of where the leaks are happening.

This might be worth a try to make the client fail sooner and with a more explicit error, in the case of a leak.

**Comment by daneshka** [comment]
Thank you  @skuruppu 
I double-checked the logs and metrics. The pods are not restarting.
Just set the `fail` option. Will update you if I see any logs.

**Comment by olavloite** [comment]
Removed the warning and added the `needs more info` label for the time being while we are waiting to see if anything can be found in the logs.

**Comment by skuruppu** [comment]
@daneshka just checking in to see how things are going by setting `fail` in your application?

**Comment by daneshka** [comment]
@skuruppu 
on the stage servers (where I added the fail flag) we only have 1 error about `session` and that happened today
```
"message":"InternalError: userId: 0, vaultId: undefined, x-forwarded-for: 10.64.208.130 \nNo resources available.  errorStack: SessionPoolExhaustedError: No resources available.\n    at SessionPool._getSession (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:699:19)\n    at getSession (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:451:40)\n    at run (/opt/tasks/node_modules/p-queue/dist/index.js:157:104)\n    at PQueue._tryToStartAnother (/opt/tasks/node_modules/p-queue/dist/index.js:105:17)\n    at PQueue._next (/opt/tasks/node_modules/p-queue/dist/index.js:48:14)\n    at run (/opt/tasks/node_modules/p-queue/dist/index.js:168:22)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at runNextTicks (internal/process/task_queues.js:64:3)\n    at processImmediate (internal/timers.js:437:9)
```
this is the session count on stage environment for the last 7 days
![image](https://user-images.githubusercontent.com/12647179/127072845-5c6a9c4e-64ec-4a3d-985f-805246798ad0.png)

looks like today there is an increase in the number of sessions which could be related to the error log.

**Comment by olavloite** [comment]
@daneshka The `SessionPoolExhaustedError` also [includes a list of stack traces](https://github.com/googleapis/nodejs-spanner/blob/cf78d4a046e40156ffa416b34faa92e3859e72d6/src/session-pool.ts#L196) that shows where all the currently in use sessions were checked out. Would it be possible for you to catch that specific error in your code and then log those messages? That should give you a hint of which parts of the code hold on to a checked out session at the moment that the error occurs.

**Comment by daneshka** [comment]
@olavloite thanks for your message.
I added the log and I'd assume it takes a few days to get a high session count and that error. I'll post the logs as soon as I see the errors.

Today we had even more session count on the stage environment and a few more instances of the `SessionPoolExhaustedError` error.
![image](https://user-images.githubusercontent.com/12647179/127183393-48fd1f77-6bde-4767-9e3b-fa8812f207b7.png)

The interesting part is all of the errors are coming from one of the queries. That query is a SELECT query with a couple of WHERE conditions. We do NOT use any transaction for that query, we just call `run` function from the database instance.

**Comment by olavloite** [comment]
> That query is a SELECT query with a couple of WHERE conditions. We do NOT use any transaction for that query, we just call run function from the database instance.

All queries require a session, so even for queries that do not use a transaction, a session will be checked out of the session pool for as long as the query is running. `database.run` will load the entire result set into memory and then close the result stream, so once `database.run` has finished, the session will be returned to the session pool. If you use `database.runStream`, the session will remain checked out until the stream is closed.

The above means that if the query that seems to be causing the problem takes a (relatively) long time, it could be that you run into the problem when a burst of requests (or other trigger, I'm not sure what exactly causes the execution of the query) come in a short period of time, and there are more than `MaxSessions` queries running in parallel. You can only have as many queries running in parallel as there can be sessions in the pool, as each query will claim its own session. The default for `MaxSessions` [is 100 for the NodeJS client](https://github.com/googleapis/nodejs-spanner/blob/f1ed7e540d939144e4bcbd0df7a2c25e8f741290/src/session-pool.ts#L157). (Note: This max applies to each pod in your setup, so the total max will be NumberOfPods * 100)

**Comment by daneshka** [comment]
2 types of errors got logged.

### The first one which happened a lot 
It has lots of items (65+) in the `messages`  array but all have the same value. so I paste only one of them here:
```
\n  \"Session leak detected!\\n    at _acquire (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:441:30)\\n    at getReadSession (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:338:14)\\n    at runStream (/opt/tasks/node_modules/@google-cloud/spanner/build/src/database.js:1839:20)\\n    at run (/opt/tasks/node_modules/@google-cloud/spanner/build/src/database.js:1648:14)\\n    at null (/opt/tasks/node_modules/@google-cloud/promisify/build/src/index.js:57:28)\\n    at Promise (null:null:null)\\n    at wrapper (/opt/tasks/node_modules/@google-cloud/promisify/build/src/index.js:42:16)\\n    

HERE IS OUR CODE TO RUN A QUERY:  database.run(query)
Please note that all stack traces goes back to one of the queries which is a SELECT statement with 4 WHERE conditions.
"
```

### The second one that happened less:
only a few items in the `messages` array and all have the same value:
```
{"message":"spanner session error (SessionPoolExhaustedError)

[\n  \"Session leak detected!\\n    at _acquire (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:441:30)\\n    at getWriteSession (/opt/tasks/node_modules/@google-cloud/spanner/build/src/session-pool.js:346:14)\\n    at getTransaction (/opt/tasks/node_modules/@google-cloud/spanner/build/src/database.js:1245:20)\\n    at null (/opt/tasks/node_modules/@google-cloud/promisify/build/src/index.js:57:28)\\n    at Promise (null:null:null)\\n    at wrapper (/opt/tasks/node_modules/@google-cloud/promisify/build/src/index.js:42:16)\\n    
HERE IS OUT CODE CALLING database.getTransaction(),
]"
```

**Comment by olavloite** [comment]
@daneshka Thank you for the additional information.

The `messages` array contain the stack traces of all the code paths that __currently hold a session that has been checked out__ of the session pool. That means that these are all potential candidates for code paths that cause a session leak, or are code paths that hold on to a session for a long time. Especially code paths that occur frequently in the `messages` array are indications of session leaks. In this case however I don't think the first code path that occurs frequently in the `messages` array is the culprit, but the second one.

My guess based on the above information would be that:
1. The first one that happens a lot is a query that takes some time to finish. The fact that it shows up many times in the `messages` array is an indication that 65+ of these queries are still running or still being processed by the client. That is a perfectly valid use case. The only thing to think about is that it means that your session pool needs at least 65+ sessions in order to be able to handle this load. The default max for a session pool is 100.
2. The second one that happens a lot less is one that could more easily create a session leak. The `database.getTransaction()` method is one that needs additional care in order to be sure that it never causes a session leak. If an error occurs during reading or writing to the transaction (even if it is an `Aborted` error), and you choose not to commit or rollback, you __must__ call `transaction.end()` in order to prevent the session that was used by the transaction to be leaked from the session pool.

It is generally recommended to use `database.runTransaction` or `database.runTransactionAsync` instead of `database.getTransaction` whenever possible. The transaction run functions will handle both aborted transactions and the session management automatically for you.

**Comment by olavloite** [comment]
@daneshka Were you able to find the root cause of the problem? Or is there anything else actionable on this issue?

**Comment by daneshka** [comment]
Hi @olavloite 

What I did:

- I made some changes to make %100 sure that we do call `transaction.end()`
- We deployed those changes into prod a few days ago and we still see the `Session leak detected` and Spanner sessions keep increasing.
- The list of stack traces again point to the same 2 lined of the code (`database.run(query)` and `database.getTransaction()`) that we discussed in the previous comments. (most of them are `database.run(query)`)
- all of the `database.run(query)`'s that we see in the list are coming from a single query (the 4th (last one) in the image below). The interesting part is, that query is not our most expensive query. We have queries with double EXECUTION_COUNT and higher AVG_LATENCY_SECONDS
![image](https://user-images.githubusercontent.com/12647179/129614415-881d97d0-a78c-40ec-ac71-27e8e29a077a.png)

What I will do:
- I will do a bigger refactor to use `database.runTransactionAsync` instead of `database.getTransaction()` but I don't expect to solve the issue with that change (because most of the issues are coming from that `database.run(query)`).


The query count is 33602 for that query in one hour, which is not a high number. What's your suggestion on that?
- Use more pods? This should not be the best option because the existing pods already have lots of free resources
- Create more database instances in each pod?
- any other solution?

**Comment by olavloite** [comment]
@daneshka 

> The query count is 33602 for that query in one hour, which is not a high number. What's your suggestion on that?

That is indeed not a high number, unless those 33602 queries are all executed within a very short fraction of one hour (see below).

> * Use more pods? This should not be the best option because the existing pods already have lots of free resources
> * Create more database instances in each pod?
> * any other solution?

I don't think you should increase the number of pods or number of database instances in each pod based on what we are seeing here. The only configuration change that I think you should consider, is increasing the max number of sessions in the session pool for the databases instances that you are using. That would mean instantiating the database instances with something like this:

```typescript
// 400 means max 400 sessions, this again means that you can execute at most 400 parallel queries and/or
// transactions using this database instance. Increase this number even further if your application has bursts
// that will cause even more queries to be executed in parallel.
const database = instance.database('some-database', {max: 400});
```

The `database.run(query)` statement should not cause any session leaks, so I really don't think that is the real problem (unless the query is taking a long time to finish, which the above information indicates that it does not).

One possibility in this case could be that the query that you are seeing is one that comes in bursts. I noticed that the table that is being queried is called `reminders`. If that query for example is coming from some timed (background) task, and very many instances of that task can be executed at the same time, then that could be the trigger for the problem (and also the reason that you are seeing this query many times in the error message). So that could mean that:
1. There's no real session leak here (or otherwise only a small one coming from something else, causing a slow build up of sessions)
2. The session pool is temporarily being exhausted by a large burst of read requests at the same time. The default session pool settings will allow a maximum of 100 sessions to be created for one database instance, which effectively means that a pod can execute at most 100 queries in parallel.

**Comment by olavloite** [comment]
@daneshka Have you been able to try the application with a larger number for max sessions? If so, did it solve the problem, or in any other way change the behavior that you are seeing?

**Comment by daneshka** [comment]
@olavloite 
I made the changes but we haven't deployed to production yet. 
I will let you know as soon as I get the results.

**Comment by skuruppu** [comment]
@daneshka just checking in to see how the prod deployment went.

**Comment by daneshka** [comment]
@skuruppu 
Thanks for the follow-up. Unfortunately, we haven't deployed that to prod yet. But our stage environment looks much better.
I will post here after I get some data from prod.

**Comment by SurferJeffAtGoogle** [comment]
It looks like this issue has been resolved.  Please re-open it if not.
