### ISSUE TITLE
Error: Timeout occurred while acquiring session on Google Cloud Run

### ISSUE THREAD

**Issue by yonghoon** [googleapis/nodejs-spanner#1465]
Our team has been trying to run our node instances on Google Cloud Run. It works well for the first one or two hours after deployment. But, every Spanner read/write access fails with the following error after 1-2 hours of deployment:
```
Error: Timeout occurred while acquiring session. 
at /usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:719:31 at new Promise (<anonymous>) 
at SessionPool._getSession (/usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:718:27) 
at getSession (/usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:451:40) 
at run (/usr/src/app/node_modules/p-queue/dist/index.js:157:104) 
at PQueue._tryToStartAnother (/usr/src/app/node_modules/p-queue/dist/index.js:105:17) 
at PQueue._next (/usr/src/app/node_modules/p-queue/dist/index.js:48:14) 
at run (/usr/src/app/node_modules/p-queue/dist/index.js:168:22) From previous event: 
at UserManager.getUsersColumns (/usr/src/app/node_modules/fam-users/dist/index.js:2012:36) 
at processTicksAndRejections (internal/process/task_queues.js:93:5) 
```

Here are the session pool options that we use for our database: 
```
{
    acquireTimeout: 15000,
    concurrency: 100,
    idlesAfter: 5,
    max: 400,
    min: 25,
    incStep: 25,
    fail: true,
}
```

For debugging purpose, we log the session pool status every 30 seconds. Here is the (normal) session pool status right after deployment:
```
{
available: 25
borrowed: 0
currentWriteFraction: 0
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 25
size: 25
totalPending: 0
totalWaiters: 0
writes: 0
}
```

Later, I found that all 25 sessions seemed to be borrowed:
```
{
available: 0
borrowed: 25
currentWriteFraction: 0.5
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 1
numWriteWaiters: 0
reads: 0
size: 25
totalPending: 25
totalWaiters: 1
writes: 0
}
```

Then, the internal state of the session pool seemed to be screwed with the -23 `borrowed` & `totalPending`:
```
{
available: 48
borrowed: -23
currentWriteFraction: 0
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 48
size: 25
totalPending: -23
totalWaiters: 0
writes: 0
}
```

Eventually, it reached the following session pool state:
```
{
available: 0
borrowed: 0
currentWriteFraction: 0.5
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 0
size: 0
totalPending: 0
totalWaiters: 0
writes: 0
}
```

When the node instance has the session pool state with all 0s, every Spanner read/write access fails with `Error: Timeout occurred while acquiring session`. The issue persists until we redeploy a new instance.

#### Environment details

  - OS: ? (Google Cloud Run)
  - Node.js version: 12.16.1
  - npm version: 6.13.4
  - `@google-cloud/spanner` version: 5.15.0

#### Steps to reproduce

  1. Run node instances on Google Cloud Run for a while.

**Comment by skuruppu** [comment]
Those stats do look problematic, and especially that you're not even able to get the pool to its maximum size before it starts misbehaving.

@olavloite if you could please take a look, that would be awesome.

**Comment by olavloite** [comment]
@yonghoon Would you mind (temporarily) trying the following options for you test setup:

```typescript
{
    idlesAfter: 500000, // This will make sure a session is (almost) never considered idle
    keepAlive: 500000, // This will practically disable the keep-alive calls for sessions
    acquireTimeout: 15000,
    concurrency: 100,
    idlesAfter: 5,
    max: 400,
    min: 25,
    incStep: 25,
    fail: true,
}
```

The `idlesAfter` and `keepAlive` settings above will effectively disable the pinging of sessions in the pool. My suspicion is that the problem in this case is caused by this pinging process that probably does not work very well on Cloud Run, because Cloud Run will disable the CPU of the container when there is no active request. This is the reason that [running background activities are discouraged on Cloud Run](https://cloud.google.com/run/docs/tips/general#avoiding_background_activities).

Especially the second state that your process is logging seems to indicate that the session pool at that moment has been trying to ping all the 25 sessions in the pool, but probably with no success:

```
{
available: 0
borrowed: 25
currentWriteFraction: 0.5
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 1
numWriteWaiters: 0
reads: 0
size: 25
totalPending: 25
totalWaiters: 1
writes: 0
}
```

The 25 borrowed sessions in this case is most probably not borrowed by your application, but by the keep-alive call that is executed in the background to try to keep the sessions alive. The `totalPending: 25` log indicates that the pool is also trying to create 25 new sessions. This is because your application is requesting a session, and all sessions are currently in use (borrowed). The pool will then try to create a new batch of sessions, with 25 being the default batch size. This session creation also seems to take a very long time, which is what is causing the error. Exactly why that is taking such a long time in this case is not (yet) clear to me, but my suspicion is that it is caused by the failed/hanging keep-alive calls.

If changing the options to disable the pinging stops this problem from occurring, we at least know that it is caused by that. If that is the case, we could look into what a reasonable next step would be to make the pinging work on Cloud Run as well.

I don't have a direct explanation for the subsequent states that your application is logging for the session pool, but I will look into that as well.

**Comment by yonghoon** [comment]
@olavloite I will try the suggested session pool options. Thanks!

**Comment by yonghoon** [comment]
`idlesAfter: 500000` & `keepAlive: 500000` don't seem to resolve the issue. FYI, we have a very small amount of traffic, generated from a couple of my mobile clients, on the Google Run services. During the entire day, Google Run scaled the services up to 2 instances at max. We had a single instance for most of the day today.

- The session started with normal numbers right after deployment:
```
{
available: 25
borrowed: 0
currentWriteFraction: 0.68
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 8
size: 25
totalPending: 0
totalWaiters: 0
writes: 17
}
```
- A few hours later, the numbers became abnormal.
```
{
available: 177
borrowed: -152
currentWriteFraction: 0.0903954802259887
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 161
size: 25
totalPending: -152
totalWaiters: 0
writes: 16
}
```
- Later, the numbers became a bit more crazier. ;-)
```
{
available: 329
borrowed: -304
currentWriteFraction: 0.0486322188449848
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO"
numReadWaiters: 0
numWriteWaiters: 0
reads: 313
size: 25
totalPending: -304
totalWaiters: 0
writes: 16
}
```

**Comment by olavloite** [comment]
> ... the session pool numbers look weird but I haven't encountered the session acquisition timeout yet.

That is good news. Please let me know if it does occur again.

> Are the negative borrowed and totalPending expected?

No, that is very strange and should not happen. I'll try to dive into that to figure out how that might happen. As far as I can tell from your statistics, the session pool still contains 25 sessions that are all available for use. The negative numbers for `borrowed` and `totalPending` are probably caused by the preparing of read/write transactions on sessions in the pool. The session pool will try to keep `writeFraction` sessions prepared with a read/write transaction, and while a session is being prepared, it is borrowed from the pool while a `BeginTransaction` RPC is executed. I think that those crazy numbers are caused by some error in that process (which is also partly a background process).

I don't know if it is possible for you, but it would be interesting to see the value of `pendingPrepare` next to `totalPending`. My suspicion is that the negative number for `totalPending` is caused fully by `pendingPrepare` (i.e. sessions that are pending being prepared with a read/write transaction, and not sessions pending creation). Would it be possible to include that in the statistics?

**Comment by yonghoon** [comment]
The session acquisition timeout still happens with the suggested session pool options. In this specific case of deployment, all the 25 borrowed ones seemed to get stuck in the pending state. The state persists forever until I redeploy services.
```
available: 0
borrowed: 25
currentWriteFraction: 0.5
isFull: false
isOpen: true
numReadWaiters: 0
numWriteWaiters: 0
pendingPrepare: 0
reads: 0
size: 25
totalPending: 25
totalWaiters: 0
uptime: 8241635
writes: 0
```
I just kicked off another round of deployment. I will update the ticket with further monitoring data tomorrow.

**Comment by yonghoon** [comment]
I encountered the session acquisition timeout again. One interesting thing about this is that the whole 25 sessions appeared to be borrowed right after the node instance was launched. There was no incoming traffic at all. 

```
{
available: 0
borrowed: 25
currentWriteFraction: 0.5
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO (25/25) #1"
numReadWaiters: 0
numWriteWaiters: 0
pendingPrepare: 0
reads: 0
size: 25
totalPending: 25
totalWaiters: 0
uptime: 300783
writes: 0
}
```

The instance has been in the state for ~2.7 hours. I had 4 mobile clients hit the instance and all 20-ish requests failed due to the session acquisition timeout for ~40 seconds (2021-09-10 23:04:15.450 PDT - 2021-09-10 23:04:54.290 PDT).

```
"Error: Timeout occurred while acquiring session.
    at /usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:719:31
    at new Promise (<anonymous>)
    at SessionPool._getSession (/usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:718:27)
    at getSession (/usr/src/app/node_modules/@google-cloud/spanner/build/src/session-pool.js:451:40)
    at run (/usr/src/app/node_modules/p-queue/dist/index.js:157:104)
    at PQueue._tryToStartAnother (/usr/src/app/node_modules/p-queue/dist/index.js:105:17)
    at PQueue._next (/usr/src/app/node_modules/p-queue/dist/index.js:48:14)
    at run (/usr/src/app/node_modules/p-queue/dist/index.js:168:22)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processTimers (internal/timers.js:494:9)"
```

Eventually, the borrowed session became available somehow.
```
{
available: 25
borrowed: 0
currentWriteFraction: 0.04
isFull: false
isOpen: true
message: "USER_DB_SESSION_POOL_INFO (0/25) #29"
numReadWaiters: 0
numWriteWaiters: 0
pendingPrepare: 0
reads: 24
size: 25
totalPending: 0
totalWaiters: 0
uptime: 10011585
writes: 1
}
```

Now, all spanner calls on the instance are successful.

**Comment by yonghoon** [comment]
Thanks for releasing the fix for the negative session count. I used the latest release (https://github.com/googleapis/nodejs-spanner/releases/tag/v5.15.2) for our backend. The negative session count issue hasn't happen yet but the session timeout still happens.

All requests arriving between 2021-09-14 07:30:55.495 PDT and 2021-09-14 07:40:45.936 PDT failed due to the session acquisition timeout:
<img width="854" alt="Screen Shot 2021-09-14 at 9 21 45 AM" src="https://user-images.githubusercontent.com/5158342/133297395-fe64754a-d2ac-4c05-ba48-2fcdd10693ba.png">

Here is the more detailed log **BEFORE** the session timeout happened:
```
{
available: 25
borrowed: 0
currentWriteFraction: 0.04
interval: 30000
isFull: false
isOpen: true
message: "SPANNER_DB_SESSION_POOL_INFO (available: 25, borrowed: 0, pending: 0, reads: 24, writes: 1) #456"
numReadWaiters: 0
numWriteWaiters: 0
pendingPrepare: 0
reads: 24
size: 25
totalPending: 0
totalWaiters: 0
uptime: 41130876
writes: 1
}
```

Here is the detailed log **WHILE** the session timeout happened (For ~10 minutes):
```
{
available: 0
borrowed: 25
currentWriteFraction: 0.5
interval: 30000
isFull: false
isOpen: true
message: "SPANNER_DB_SESSION_POOL_INFO (available: 0, borrowed: 25, pending: 25, reads: 0, writes: 0) #457"
numReadWaiters: 1
numWriteWaiters: 0
pendingPrepare: 0
reads: 0
size: 25
totalPending: 25
totalWaiters: 1
uptime: 41160883
writes: 0
}
```

Here is the detailed log **AFTER** the session timeout happened:
```
{
available: 25
borrowed: 0
currentWriteFraction: 0
interval: 30000
isFull: false
isOpen: true
message: "SPANNER_DB_SESSION_POOL_INFO (available: 25, borrowed: 0, pending: 0, reads: 25, writes: 0) #476"
numReadWaiters: 0
numWriteWaiters: 0
pendingPrepare: 0
reads: 25
size: 25
totalPending: 0
totalWaiters: 0
uptime: 41753026
writes: 0
}
```

**Comment by olavloite** [comment]
@yonghoon What does `interval: 30000` mean in the above logging? Is that the setting for `idlesAfter` and `keepAlive`? If so, is that the actual value in milliseconds, or is it in some other unit?

**Comment by yonghoon** [comment]
@olavloite `30000` (=30s) is the logging interval. I used the same session pool options that you suggested:
```
{
    idlesAfter: 500000, // This will make sure a session is (almost) never considered idle
    keepAlive: 500000, // This will practically disable the keep-alive calls for sessions
    acquireTimeout: 15000,
    concurrency: 100,
    idlesAfter: 5,
    max: 400,
    min: 25,
    incStep: 25,
    fail: true,
}
```

**Comment by olavloite** [comment]
@yonghoon Cloud Run very recently introduced a new feature that should help mitigate this kind of problems: https://cloud.google.com/blog/products/serverless/cloud-run-gets-always-on-cpu-allocation

Would it be possible for you to try that option out to see if that solves this problem?

**Comment by yonghoon** [comment]
@olavloite I will try with the new allocation mode. Thanks for the suggestion!

**Comment by olavloite** [comment]
@yonghoon Did you have a chance to try it out with the new allocation mode? And did it make any difference?

**Comment by skuruppu** [comment]
I downgraded the priority since we haven't had an update in a while. @yonghoon let us know how your experiments went.

**Comment by olavloite** [comment]
Closing this as we haven't heard back in a while. @yonghoon Please feel free to reopen if the problem persists.
