### ISSUE TITLE
Spanner session count growing well beyond limit

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#184]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.6
  - npm version: v5.6.0
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce
Will create some if needed

I am running a replicated set of APIs using this library with the following session pool configuration:
```
max: 700
min: 300
concurrency: 200
idlesAfter: 4
maxIdle: 1
acquireTimeout: 4000
writes: 50
```

You may have noticed the `writes: 50` value down there as being a bit odd.  I had forgotten this value was a percentage and accidentally rolled out an update with this config.  From my understanding of this configuration if I have 10 API instances I should see a max session count for the Spanner instance (assuming these APIs are the only ones connecting) of 7000 sessions. 

However when I deployed this change I went from 2,401 sessions all the way up to 50,092 sessions which put me over the session limit for my 5 node Spanner instance.  I understand that doing 50% write sessions is overly-aggressive however I keep seeing this go over what I view as the theoretical session limit which is very concerning considering once that happens all requests start to fail and it is non-trivial to free up these sessions by bouncing the service or something similar.  Please let me know if I'm missing something in understanding the pooling logic.

**Comment by callmehiphop** [comment]
@walshie4 I think this is a documentation failure on our part, but writes should be a decimal representing the percentage. The code assumes it comes in as a decimal and we calculate the number of sessions to create via `min * writes`.

I'm going to update the docs and I think scrub the `writes` value for whole numbers greater than 1, since this is a pretty easy mistake to make, but in the mean time you just need to update your writes value to `0.5`.

**Comment by walshie4** [comment]
Thank you for the clarification & regression test case @callmehiphop.  The behavior now makes sense 👍

**Comment by walshie4** [comment]
I'll actually leave this open until the PR is merged
