### ISSUE TITLE
Database.runTransactionAsync should check that the error returned can be re-tried instead of the indefinite while(true) loop

### ISSUE THREAD

**Issue by odeke-em** [googleapis/nodejs-spanner#2166]
If we examine the code for Database.runTransactionAsync, it invokes a while(true) loop retrying on any error without differentiating if the error can be retried or not and the only way to break out of that loop is by throwing an exception https://github.com/googleapis/nodejs-spanner/blob/2a19ef1af4f6fd1b81d08afc15db76007859a0b9/src/database.ts#L3370-L3406

The only way I can test out functionality of that code in error is by throwing an exception and there aren't tests for what happens with a variety of errors. Let's please add them.

**Comment by surbhigarg92** [comment]
@odeke-em This is by design. This `while` loop is added for retrying [session not found](https://github.com/googleapis/nodejs-spanner/blob/2a19ef1af4f6fd1b81d08afc15db76007859a0b9/src/database.ts#L3367) error. 

Other errors will not be retried and the error will be thrown from [here](https://github.com/googleapis/nodejs-spanner/blob/2a19ef1af4f6fd1b81d08afc15db76007859a0b9/src/database.ts#L3402)

Please feel free to re-open the issue, if this doesn't satisfy your error.
