### ISSUE TITLE
Write parent row with interleaved child row within same transaction

### ISSUE THREAD

**Issue by splawndive** [googleapis/nodejs-spanner#324]
Hi, I'd like some clarification on the docs posted here https://cloud.google.com/spanner/docs/transactions#rw_transaction_semantics

```
Transaction reads don't see the same transaction's writes. It's important to note that reads do not see the writes that are buffered in the same transaction. Writes are buffered until the end of the transaction and aren't visible to any reads until the transaction is committed. This is because when you buffer mutations, they're stored locally in your client and aren't sent to the server until commit time. Reads however, are sent directly to the server.
```

Does this mean that I'm unable to both write a row to a parent table, and a child row which interleaves with that row within the same transaction?
In the program that I'm writing, using the following steps
1. write one row to the parent table using `transaction.insert`
2. write one row to the interleaved table using `transaction.insert`
3. make a call to `transaction.commit`
the call to `commit` results in the transaction being aborted with error code 5 `NOT_FOUND`, which seems to indicate the above.  Is that expected?

#### Environment details
  - `@google-cloud/spanner` version: 2.0.0

**Comment by teddychan** [comment]
@splawndive can you provide your code here and maybe we can help.
We did the same thing without this error.

**Comment by splawndive** [comment]
hey thanks for the reply

sorry for the slow response, but I actually ended up being able to work through this one myself.  the issue ended up just being some wonkiness with the IDs i was using/passing around within my application, not within spanner itself.

**Comment by geudrik** [comment]
@splawndive can you elaborate at all? I've found this thread having run across the same issue seemingly. 

I've got a table interleaved with a parent, I insert a row into the parent, commit, and using the same session (since flush wasn't working/resulted in the same issue), then try to add a few rows to the child table, and I wind up with errors like the following 

`google.api_core.exceptions.NotFound: 404 Parent row for row [234eeca9-2a04-4885-a4f4-5096f664378e,0459f48e-54f8-486d-85ee-77635cbd6472] in table rel_malware_communicates_with is missing. Row cannot be written.`

I am using the spanner sqlalchemy dialect in this case, but it sounds like the same issue and from what I can tell, my DDL / Tables are created correctly.

**Comment by geudrik** [comment]
I turned Echo on in sqlalchemy, and here's the query being executed

```
INSERT INTO
rel_malware_communicates_with (
    id,
    malware_id,
    ipaddress_id,
    domain_id,
    url_id
)
VALUES
(
    '3b3c74ec-ed89-4dfe-aa1c-f3dc4d36ab51',
    '16af14ed-2544-4ace-b093-3e050538acbf',
    null,
    '00d48439-2379-41ef-9d95-ed16ec6919a4',
    null
)
```

Here's the DDL for the table (and yes, that ID for `malware_id` exists in `ob_malware`)
```
CREATE TABLE rel_malware_communicates_with (
	id STRING(MAX) NOT NULL,
	malware_id STRING(MAX) NOT NULL,
	ipaddress_id STRING(MAX),
	domain_id STRING(MAX),
	url_id STRING(MAX),
	FOREIGN KEY (domain_id) REFERENCES ob_domain(id),
	FOREIGN KEY (ipaddress_id) REFERENCES ob_ipaddress(id),
	FOREIGN KEY (malware_id) REFERENCES ob_malware(id),
) PRIMARY KEY (id, malware_id),
INTERLEAVE IN PARENT ob_malware
```

Clearly there's something with interleaving I'm missing here :S
