### ISSUE TITLE
System tests deletes all running instances of another test run

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-spanner#365]
Currently the system tests are deleting all instances matching `filter: 'labels.gcloud-tests:true'`. This is problematic when we are running parallel tests on the now- Kokoro system-test enabled PRs and continuous integration builds.

We need to label instances with a uuid prefix to distinguish them between builds, and let the `after` hook of Mocha clean up the instances based on the prefix.

**Comment by kinwa91** [comment]
cc @callmehiphop @stephenplusplus

**Comment by stephenplusplus** [comment]
> We need to label instances with a uuid prefix to distinguish them between builds, and let the after hook of Mocha clean up the instances based on the prefix.

Ideally, each test run should be able to clean up after itself, but we inevitably end up with stale resources. The point of the label was to be unique for our library, but not unique to the test run, so that we can clean up from previous builds that went wrong.

Maybe we could use an env var, `GOOGLE_CLOUD_TEST_PREFIX`, that defaults to `gcloud-tests`, but Kokoro can set to something like `kokoro-tests`?

**Comment by stephenplusplus** [comment]
I believe another solution we used before was deleting resources that were >= 1 hour old. Doing that requires reading into the metadata to get the appropriate property to determine the age, so it's a bit harder to generalize that logic. But, if it's just instances we want to figure out, it should be manageable.

**Comment by callmehiphop** [comment]
What if we modified our tests to only clean up what we created within that pass and then modified the nightly build to delete all the instances after system tests run.

**Comment by stephenplusplus** [comment]
That sounds pretty solid to me. There's still a chance for resource collision, but pretty the odds are pretty small that we'd be merging an important PR overnight, when the nightlies would be running.

On the other hand, I recall Spanner being pretty limiting with resources (Instances, maybe?). So, I wonder if it would be possible that, say, 3 CI runs fail to clean up properly, which created x resources each. If that reached the Spanner limit, all of the CI runs for the remainder of the day, until the next nightly run would error.

That scenario should be relatively unlikely, however these things could coerce it:

- User-error in the system test file that commented out a clean-up line, or otherwise blocked the clean up from running
- CI process exits unnaturally, before the clean up step is reached
- ?

**Comment by stephenplusplus** [comment]
I believe the prefix solution was the most robust one we found, and was borrowed by some of the other languages as well. The concept of parallel runs is new for us with system tests (Kokoro running at the same time as Circle).

@JustinBeckwith do you know of anything that works reliably here?

**Comment by JustinBeckwith** [comment]
We could just disable CircleCI presubmit and continuous runs here right?

**Comment by kinwa91** [comment]
> We could just disable CircleCI presubmit and continuous runs here right?

We'll still possibly have parallel runs from each PRs and/or continuous tests.

I'm in favor of unique prefix + nightly cleanup of stale resource (perhaps been running x+ hour?)
