### ISSUE TITLE
`npm test` fails on Timezones that are greater than UTC.

### ISSUE THREAD

**Issue by sulaysumaria** [googleapis/nodejs-spanner#526]
#### Environment details

  - OS: Linux (WSL)
  - Node.js version: 11.9.0
  - npm version: 6.8.0
  - `@google-cloud/spanner` version: 2.2.1

#### Steps to reproduce

  1. Change Timezone to UTC + 01:00 (Anything that is ahead of UTC).
  2. Run `npm test`.
  3. The test `codec > SpannerDate > should create an instance from a string` fails.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sulaysumaria** [comment]
As a solution, We can change the way the value is assigned to `this.value` in `SpannerDate` constructor class.

**Comment by callmehiphop** [comment]
@stephenplusplus @JustinBeckwith I think @sulaysumaria has uncovered a off-by-one error regarding our handling of [`DATE` types](https://cloud.google.com/spanner/docs/data-types#date-type).

The native Date object actually infers a timezone based on the format of date string. If formatted as ISO 8601 (`Y-m-d`) it infers UTC-0, otherwise it will assume local time. This is problematic for us because we currently generate the `DATE` string via `toISOString()` which can give us the wrong date for UTC+n timezones.

I'm not sure what the best way to resolve this issue would be, but right now my brain thinks that our best bet might be to check if the input is an ISO string and if so, manually parse/set the time to infer the local time.

Thoughts?

**Comment by sulaysumaria** [comment]
@callmehiphop can we exclude the test for this SpannerDate? It is causing npm test to fail for UTC+n.

**Comment by callmehiphop** [comment]
@sulaysumaria I don't think we should do that, seems like the test exposed a bug for UTC+n timezones, I'm working on a fix for it though.
