### ISSUE TITLE
grpc-js does not work with spanner

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-spanner#555]
The tests - they fail!  This should be fixied.

**Comment by alexander-fenster** [comment]
Not on my plate. grpc-gcp should support grpc-js, that's for @WeiranFang :)

**Comment by alexander-fenster** [comment]
(and I guess we're waiting for @types/grpc here)

**Comment by JustinBeckwith** [comment]
@alexander-fenster I want to make sure we have the right work items and assignees here.  Do we have separate bugs tracking those things in the appropriate repos?

**Comment by alexander-fenster** [comment]
I created https://github.com/GoogleCloudPlatform/grpc-gcp-node/issues/41 in their repo.

**Comment by skuruppu** [comment]
@olavloite, if you could discuss this with @alexander-fenster and see if there's anything that can be done to unblock this, that would be great.

**Comment by olavloite** [comment]
@alexander-fenster Could you provide me with some additional context on what this is about? From the description in this issue, it's not clear to me exactly what we are waiting for / what is failing / whether we still need to wait etc.

**Comment by alexander-fenster** [comment]
@olavloite Spanner is the only client library that uses [grpc-gcp](https://www.npmjs.com/package/grpc-gcp) module, that was implemented across all languages by @WeiranFang some time about a year ago. This implementation works with legacy `grpc` but not with `@grpc/grpc-js`, so this library cannot switch to `@grpc/grpc-js` until this module is fixed. The linked issue https://github.com/GoogleCloudPlatform/grpc-gcp-node/issues/41 is exactly about that :)  

I think the `@types/grpc` package that is mentioned in that issue was expected to export common types between `grpc` and `@grpc/grpc-js`. From what I understand, it will never appear (the gRPC team will not ship it), so it does not block working on the `@grpc/grpc-js` support.

**Comment by WeiranFang** [comment]
Hi @alexander-fenster, `grpc-gcp` relies on client interceptors from the legacy `grpc`. And the PR for interceptors for `grpc-js` is pending: https://github.com/grpc/grpc-node/pull/1184. We will work on the migration once we have client interceptors implemented in `grpc-js`. I'll update on GoogleCloudPlatform/grpc-gcp-node#41 since `@types/grpc` is not going to be implemented.

**Comment by alexander-fenster** [comment]
Thank you for this update @WeiranFang!

**Comment by skuruppu** [comment]
Thanks @olavloite, @alexander-fenster and @WeiranFang for the update.

Just to make sure I understand, we can't work on this until GoogleCloudPlatform/grpc-gcp-node#41 is fixed?

**Comment by alexander-fenster** [comment]
@skuruppu That's right.

**Comment by skuruppu** [comment]
I believe #928 is the work that went into fixing this issue? Correct me if I'm wrong @alexander-fenster.

**Comment by JustinBeckwith** [comment]
Yes!
