### ISSUE TITLE
date, float and int static methods not documented

### ISSUE THREAD

**Issue by WaldoJeffers** [googleapis/nodejs-spanner#59]
#### Environment details

  - OS: GCP
  - Node.js version: 8.9.x
  - npm version: 5.5
  - @google-cloud/spanner version: 0.8.2

#### Steps to reproduce
[According to the docs](https://cloud.google.com/nodejs/docs/reference/spanner/0.8.x/Spanner#date), the `date`, `float` and `int` helper functions only seem to be available on `Spanner` class instances. This can be frustrating if you are creating your own utility functions, like this one:
```js
// ./utils/formatUser.js
import Spanner from '@google-cloud/spanner';
const spanner = Spanner() // But why do I have to instanciate Spanner here though?
export default (user) => ({
  balance: spanner.float(user.balance),
  bookCount: spanner.int(user.bookCount),
})
```
It would be much better if these utility functions were actually *static* methods available on `Spanner` (this would save you the trouble of creating a `Spanner` instance):
```js
// ./utils/formatUser.js
import Spanner from '@google-cloud/spanner'
export default (user) => ({
  balance: Spanner.float(user.balance),
  bookCount: Spanner.int(user.bookCount),
})
```
But much to my surprise, this code seems to *actually work*. So maybe we only need to update the docs?

Thanks in advance!

**Comment by callmehiphop** [comment]
@stephenplusplus part of me thinks maybe we should just dump the instanced versions of these, wdyt?

**Comment by vkedia** [comment]
I agree we should just dump the instance methods. I can't think of a reason why anyone would use them instead of static methods.

**Comment by stephenplusplus** [comment]
The reason they're there is because the easiest way to get up and going with the library is with a single statement:

```js
const spanner = require('@google-cloud/spanner')({ ... })
```

I put the type methods on the instance because, otherwise, the user would have to change "the easiest way to get up and going", and split out the require statement from the instance-creation one.

I think both have their place, and since we already have them, I would vote we just keep them as to not disturb any existing codebases, without a clear benefit why the user would have to rewrite their code.

(Also, BigQuery, Datastore, and possibly others follow the same Static|Instance pattern)

**Comment by callmehiphop** [comment]
Ah, right. Is there something we can do get the docs to show up for them in the current state then (@alias maybe)? Or do we need to declare those docs separately?

**Comment by stephenplusplus** [comment]
cc @jmdobry !

**Comment by vkedia** [comment]
I think there is a benefit to removing the instance methods. We should not encourage people creating a spanner object just to access these methods. Creating a spanner object is expensive since, as far as I can tell, it involves setting up grpc connection.
I would say in anything but toy applications users should be using the static methods, unless they pass around a single instance of spanner object everywhere which is again painful.

**Comment by stephenplusplus** [comment]
> Creating a spanner object is expensive since, as far as I can tell, it involves setting up grpc connection.

Not sure on this-- @callmehiphop ?

> unless they pass around a single instance of spanner object everywhere which is again painful.

I don't think we need to know anything about their application structure to say that having the instance methods would be a convenience to them. It's perfectly plausible to me that they would need to create an `Int` type from the same place they call `insert`.

**Comment by vkedia** [comment]
But at the place they call `insert`, they need not have access to the spanner object. Really `spanner` object is useful to only get a `database` object out of it and then there is no need to keep it around.

**Comment by callmehiphop** [comment]
> Creating a spanner object is expensive since, as far as I can tell, it involves setting up grpc connection.

I don't believe that's true, I think we lazily instantiate grpc clients, so unless they're actually making requests it should be ok. 

@stephenplusplus not sure if it matters, but I assume eventually people will shift towards `import` instead of `require` which would prohibit users from instantiating in this way (I think).

**Comment by jmdobry** [comment]
Those methods are currently both instance methods and static methods, but only properly documented as instance methods. #60 properly documents them as both

**Comment by jmdobry** [comment]
> @stephenplusplus not sure if it matters, but I assume eventually people will shift towards import instead of require which would prohibit users from instantiating in this way (I think).

It's not the switch to `import` that will do it, but the switch to ES2015 classes. Once we have

```js
class Spanner {
 // ...
}
```

then we get

```js
new Spanner(); // works
Spanner(); // throws "TypeError: Class constructor Spanner cannot be invoked without 'new'"
```

**Comment by vkedia** [comment]
Will this not create a grpc channel:
https://github.com/googleapis/nodejs-spanner/blob/master/src/index.js#L210

**Comment by stephenplusplus** [comment]
Since it sounds like the instance methods won't be as beneficial when users are forced to localize a `Spanner` variable, I'm neutral about when we choose to get rid of them.

**Comment by vkedia** [comment]
My question on this is still unanswered:
Does create a spanner object create a new channel?

Also given that there is no clear benefit of having these methods, I strongly feel we should remove them now. We have to do this before GA in any case since it is a breaking change.

**Comment by callmehiphop** [comment]
@vkedia sorry, I'm a little fuzzy about the internals of gRPC but we do not instantiate a grpc client until the first time we make an actual request. The code you were referencing (`GrpcService`) is a custom abstraction layer we wrote.

**Comment by stephenplusplus** [comment]
https://github.com/googleapis/nodejs-spanner/issues/65

**Comment by vkedia** [comment]
@callmehiphop That is good to know. But we might want to change that behavior in future to make sure that initial few requests that users make do not block for channels to be established. Anyways let us discuss on the new issue.
