### ISSUE TITLE
Using unshift() & splice() for stack in the session pool leads to a poor performance. 

### ISSUE THREAD

**Issue by hengfengli** [googleapis/nodejs-spanner#767]
#### Environment details

  - OS:macOS 10.14.6
  - Node.js version:v13.3.0
  - npm version:6.13.2
  - `@google-cloud/spanner` version:4.4.1

#### Steps to reproduce

`this._inventory[type]` returns an array. Currently, we use `unshift` to prepend a session to the front of the array. I believe this is very low efficient because every time you have to shift all elements in order to prepend an element into an array (a O(n) operation). 

https://github.com/googleapis/nodejs-spanner/blob/f419e27e24eb8df78633d8245c364a709e58d007/src/session-pool.ts#L867

When we remove it from the array, we use `splice` to modify the original array. If the element is the first one, we also need to move all the rest of elements (a O(n) operation). 

https://github.com/googleapis/nodejs-spanner/blob/f419e27e24eb8df78633d8245c364a709e58d007/src/session-pool.ts#L522-L528

https://github.com/googleapis/nodejs-spanner/blob/f419e27e24eb8df78633d8245c364a709e58d007/src/session-pool.ts#L538-L542

If we use the array as a LIFO stack, we should use push & pop (O(1) operations). 

#### Benchmarking test

```typescript
var array = [];
const runs = 100000;

var start = Date.now();
for (var _i = 0; _i < runs; _i++) {
    array.push(_i);
}
console.log("push time:", Date.now() - start);

start = Date.now();
for (var _i = 0; _i < runs; _i++) {
    array.pop();
}
console.log("pop time:", Date.now() - start);

array = [];
start = Date.now();
for (var _i = 0; _i < runs; _i++) {
    array.unshift(_i);
}
console.log("unshift time:", Date.now() - start);

var index;
start = Date.now();
for (var _i = 0; _i < runs; _i++) {
    index = array.indexOf(_i);
    array.splice(_i, 1);
}
console.log("lookup & splice time:", Date.now() - start);
```

Output: 

```bash
push time: 5
pop time: 4
unshift time: 856
lookup & splice time: 2960
```

**Comment by hengfengli** [comment]
@olavloite @skuruppu 

Is it possible that when the customer sets a very high `max`, like 150k, this would cause high delays to add a new session and borrow a session?

**Comment by olavloite** [comment]
@hengfengli 
That's an interesting find. I've done some additional testing, and I agree with you that using `pop` and `push` would be better than the current `unshift` and `splice` calls as those better describe what we are doing.

The performance difference in the actual session pool implementation seems to be smaller than what the above values might suggest. I'm not able to find any significant difference between using `push` and `unshift` when using an array containing actual session objects. It might be that the Javascript compiler is able to internally optimize this loop:

```
for (var _i = 0; _i < runs; _i++) {
    array.push(_i);
}
```

as it is filling an array with a simple range of integers. When I execute the same loop using both `push` and `unshift`, but filling the array with session objects instead of integers, there does not seem to be any significant performance difference between the two methods.

`pop` does however seem to have a significant performance advantage above `splice`, although smaller than the above example seems to imply. The session pool is always calling `splice(0, 1)`, which means that it in reality only removes the first element of the array. The above example removes elements from the array at all possible indices of the array.

So my conclusion at this moment would be:
1. Yes, we should definitely use `push` and `pop` instead of `unshift` and `splice`, as these do perform better, and also better represent what we want to do.
1. I don't think the actual performance difference will be really significant in a real-life application, even with a session pool size of 150k. My testing used a pre-filled session pool with 25,000 sessions, and I measured a 500ms difference when doing 25,000 cycles of getting and returning a session from this pool.

**Comment by hengfengli** [comment]
@olavloite 

I did my test with `25000`: 

```bash
# 25000 times of _borrowFrom() & _release()

# original: unshift() + splice()
borrow time: 433ms
release time: 41ms

# updated: push() + pop()
borrow time: 8ms
release time: 8ms
```

I agree that when the number of sessions is small, the performance improvement is not obvious. 

In terms of the comparison between `push` and `unshift` for an array, I don't think it's related to the type of the element although I'm not sure about Javascript compiler optimization. But just from the implementation of an `array` data structure, I believe that there is a big performance difference between appending an element and prepending an element to an array. 

> The session pool is always calling splice(0, 1), which means that it in reality only removes the first element of the array.

This is not fully correct. The original code is: 

```javascript
# _borrowFrom
const session = this._inventory[type][0]; 

# _borrow
const index = this._inventory[type].indexOf(session);
this._inventory[type].splice(index, 1);
```

There is a chance that a thread `A` gets the first session in `this._inventory` but before the session is removed from `this._inventory`, `this._inventory` has been updated by another thread `B` via `unshift()`. Therefore, the session got by `A` now is the second one in `this._inventory`. So it is not always calling `splice(0, 1)`. 

I put my testing code here as well: 

```javascript
const { Spanner } = require('@google-cloud/spanner');

const projectId = "e2e-debugging";
const instanceId = "hengfeng-test-instance";
const databaseId = "test-db";

async function runTest() {

  // Creates a client
  const spanner = new Spanner({
    projectId: projectId,
  });

  const numSessions = 25000;

  // Gets a reference to a Cloud Spanner instance and database
  const instance = spanner.instance(instanceId);
  const database = instance.database(databaseId, {
    max: numSessions,
    min: numSessions,
    concurrency: numSessions/2,
    writes: 0,
    // fail: true,
  });

  setTimeout(async function(){ 
    database.display();

    const sessions = [];

    var start = new Date().getTime();
    var end = new Date().getTime();

    for (var _i = 0; _i < numSessions; _i++) {
      sessions.push(database.pool_._borrowFrom("readonly"));
    }

    end = new Date().getTime();
    console.log('borrow time: %dms', end-start);

    console.log(sessions.length);

    start = new Date().getTime();

    for (var _i = 0; _i < numSessions; _i++) {
      database.pool_._release(sessions[_i]);
    }

    end = new Date().getTime();
    console.log('release time: %dms', end-start);

    console.log("closing the database connection.");
    await database.close().catch((err) => {
      console.log(err);
    });
  }, 30000);
}

runTest();
```

I updated `_borrowFrom()` and `_release()` methods in session-pool.js: 
```javascript
    _release(session) {
        const type = session.type;
        
        // this._inventory[type].unshift(session);
        this._inventory[type].push(session);

        this._inventory.borrowed.delete(session);
        this._traces.delete(session.id);
        this.emit('available');
    }

    _borrowFrom(type) {
        // const session = this._inventory[type][0];
        
        const session = this._inventory[type].pop();

        this._inventory.borrowed.add(session);
        return session;
    }
```

**Comment by olavloite** [comment]
Thank you for the extensive information and test results. I think this definitely shows that we should change from `unshift` and `splice` to `push` and `pop`. The test results you got using 25,000 sessions seem reasonable, and although it won't make a huge difference, there is still some gain. And I think it makes the intention of the code clearer, as we want to consider the session pool a stack.

> There is a chance that a thread A gets the first session in this._inventory but before the session is removed from this._inventory, this._inventory has been updated by another thread B via unshift(). Therefore, the session got by A now is the second one in this._inventory. So it is not always calling splice(0, 1).

That actually shouldn't be a possibility in Node, as this is executed using a single thread.
